/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tkym_labs_sharedmem_win_BaseNamedObjectsJni */

#ifndef _Included_com_tkym_labs_sharedmem_win_BaseNamedObjectsJni
#define _Included_com_tkym_labs_sharedmem_win_BaseNamedObjectsJni
#ifdef __cplusplus
extern "C" {
#endif
#undef com_tkym_labs_sharedmem_win_BaseNamedObjectsJni_PAGE_READONLY
#define com_tkym_labs_sharedmem_win_BaseNamedObjectsJni_PAGE_READONLY 2L
#undef com_tkym_labs_sharedmem_win_BaseNamedObjectsJni_PAGE_READWRITE
#define com_tkym_labs_sharedmem_win_BaseNamedObjectsJni_PAGE_READWRITE 4L
#undef com_tkym_labs_sharedmem_win_BaseNamedObjectsJni_PAGE_WRITECOPY
#define com_tkym_labs_sharedmem_win_BaseNamedObjectsJni_PAGE_WRITECOPY 8L
#undef com_tkym_labs_sharedmem_win_BaseNamedObjectsJni_FILE_MAP_COPY
#define com_tkym_labs_sharedmem_win_BaseNamedObjectsJni_FILE_MAP_COPY 1L
#undef com_tkym_labs_sharedmem_win_BaseNamedObjectsJni_FILE_MAP_WRITE
#define com_tkym_labs_sharedmem_win_BaseNamedObjectsJni_FILE_MAP_WRITE 2L
#undef com_tkym_labs_sharedmem_win_BaseNamedObjectsJni_FILE_MAP_READ
#define com_tkym_labs_sharedmem_win_BaseNamedObjectsJni_FILE_MAP_READ 4L
/*
 * Class:     com_tkym_labs_sharedmem_win_BaseNamedObjectsJni
 * Method:    createFileMapping
 * Signature: (Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_com_tkym_labs_sharedmem_win_BaseNamedObjectsJni_createFileMapping
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     com_tkym_labs_sharedmem_win_BaseNamedObjectsJni
 * Method:    openFileMapping
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_tkym_labs_sharedmem_win_BaseNamedObjectsJni_openFileMapping
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_tkym_labs_sharedmem_win_BaseNamedObjectsJni
 * Method:    mapViewOfFile
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_tkym_labs_sharedmem_win_BaseNamedObjectsJni_mapViewOfFile
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_tkym_labs_sharedmem_win_BaseNamedObjectsJni
 * Method:    unmapViewOfFile
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tkym_labs_sharedmem_win_BaseNamedObjectsJni_unmapViewOfFile
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tkym_labs_sharedmem_win_BaseNamedObjectsJni
 * Method:    createByteBuffer
 * Signature: (IJ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_tkym_labs_sharedmem_win_BaseNamedObjectsJni_createByteBuffer
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_tkym_labs_sharedmem_win_BaseNamedObjectsJni
 * Method:    closeHandle
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tkym_labs_sharedmem_win_BaseNamedObjectsJni_closeHandle
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tkym_labs_sharedmem_win_BaseNamedObjectsJni
 * Method:    createMutex
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tkym_labs_sharedmem_win_BaseNamedObjectsJni_createMutex
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tkym_labs_sharedmem_win_BaseNamedObjectsJni
 * Method:    openMutex
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tkym_labs_sharedmem_win_BaseNamedObjectsJni_openMutex
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tkym_labs_sharedmem_win_BaseNamedObjectsJni
 * Method:    releaseMutex
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_tkym_labs_sharedmem_win_BaseNamedObjectsJni_releaseMutex
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tkym_labs_sharedmem_win_BaseNamedObjectsJni
 * Method:    waitForSingleObject
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_tkym_labs_sharedmem_win_BaseNamedObjectsJni_waitForSingleObject
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
